version: '3.4'
services:
  db:
    image: mysql:5.7
    restart: ${RESTART}
    ports:
        - 81:80
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
        - db:/var/lib/mysql
    networks:
      - api
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: ${RESTART}
    ports:
        - '80:80'
    volumes:
        - ".:/var/www/html"
        - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    depends_on:
      - db
    networks:
      - api
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: ${RESTART}
    ports:
      - '82:80'
    networks:
      - api
networks:
  api:
volumes:
  wordpress:
  db:
  phpmyadmin:
